Return-Path: <linux-input-owner@vger.kernel.org>
X-Original-To: lists+linux-input@lfdr.de
Delivered-To: lists+linux-input@lfdr.de
Received: from out1.vger.email (out1.vger.email [IPv6:2620:137:e000::1:20])
	by mail.lfdr.de (Postfix) with ESMTP id 611947BF3C6
	for <lists+linux-input@lfdr.de>; Tue, 10 Oct 2023 09:08:43 +0200 (CEST)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S1378097AbjJJHIm (ORCPT <rfc822;lists+linux-input@lfdr.de>);
        Tue, 10 Oct 2023 03:08:42 -0400
Received: from lindbergh.monkeyblade.net ([23.128.96.19]:54208 "EHLO
        lindbergh.monkeyblade.net" rhost-flags-OK-OK-OK-OK) by vger.kernel.org
        with ESMTP id S1379429AbjJJHIl (ORCPT
        <rfc822;linux-input@vger.kernel.org>);
        Tue, 10 Oct 2023 03:08:41 -0400
Received: from mail-yb1-xb36.google.com (mail-yb1-xb36.google.com [IPv6:2607:f8b0:4864:20::b36])
        by lindbergh.monkeyblade.net (Postfix) with ESMTPS id D1B8BBA;
        Tue, 10 Oct 2023 00:08:39 -0700 (PDT)
Received: by mail-yb1-xb36.google.com with SMTP id 3f1490d57ef6-d81f079fe73so6183148276.3;
        Tue, 10 Oct 2023 00:08:39 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20230601; t=1696921719; x=1697526519; darn=vger.kernel.org;
        h=cc:to:subject:message-id:date:from:mime-version:from:to:cc:subject
         :date:message-id:reply-to;
        bh=YeqyIlvho61HfPbMrSU3EeErwNBNPMJPgY5XJ95ZVZE=;
        b=UtyXdDpO4OD9Ij3vNND0q46ob7+JnIf+64v65gNb2XiFACfSD1xV8ksj+KOQX5GMyi
         XqwtT10Fp52IcMF3UuOMFM29zFlG/CIVjqvop3bgFmTAKia5Qh8E7VSSQncWT83jeBa3
         kLH0qhcqTwqip3SPa0Kt5DnBJ1wW+gh0R6BjfJpnKjy9EgP9FUc4VOQSa6gOnpNHEC6q
         duyfyPXald5hf+OXZu/5iu81eNTarF1mXzCmxDJlGtDvQYEPS23/4thAGaf3iGKgsLPS
         8dctiu6OeWvKhsfZEj2/RppnT5CbA5rnl3oPM+O+5JzVdPiPzZfWlrPaG2xxVsAl5KRb
         y3qg==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20230601; t=1696921719; x=1697526519;
        h=cc:to:subject:message-id:date:from:mime-version:x-gm-message-state
         :from:to:cc:subject:date:message-id:reply-to;
        bh=YeqyIlvho61HfPbMrSU3EeErwNBNPMJPgY5XJ95ZVZE=;
        b=XfG+zXNeOkfMTm4R4xK2sjKmcSQIikfT1aLwNbegIOgmZ0KYS49GihrZch03BC42mA
         p24F6AR+iH0qxU5a51XUfrCA6fMeJ/T4VwdihFNv8J+h0LL3K5dwmf4hdMgH+Uccclyt
         9Ij/vSyzJ4AAyT4ix03OwFtfHUdyaVvv4lM7ikhsTqxHiRzVw92BL5ZzfVbUZAB5CRDW
         GCsWTLywf/5XIx4uXfv5iLHm6KUqNcqGpEZ7gVRPCXpP2zXu2VHazqIqdvNzS8ZB/vRX
         bIRg9X/6EjBX/ShON7u/7h2zMPtboSuyUO85Xdg+yhZtClQ6+CijO1gda+5C1fFdnXxA
         jP7Q==
X-Gm-Message-State: AOJu0Yxm49qz9fDUK8DoObZVVymrELU6gyVbFAucS1o4VTZbN/K2qcsi
        UsPTWra04to7aPGD8dCip1QYZPrcTEzTpg5SiEyAW/Daq6M=
X-Google-Smtp-Source: AGHT+IGEox/05sXpMcKhg4323i9rWS4KId6Al9MV6v8euRF/lWViJgCDs0xDXw1wli8zc+3jAtdKAE13Li4OVNV5ywo=
X-Received: by 2002:a5b:ac5:0:b0:d11:2a52:3f35 with SMTP id
 a5-20020a5b0ac5000000b00d112a523f35mr15121360ybr.20.1696921718946; Tue, 10
 Oct 2023 00:08:38 -0700 (PDT)
MIME-Version: 1.0
From:   John Salamon <salamonj9@gmail.com>
Date:   Tue, 10 Oct 2023 17:38:27 +1030
Message-ID: <CA+fyA4RABYNPZZSk9+9U51u53kbSzqgwdi1KDDGRxXi8q5TtxQ@mail.gmail.com>
Subject: uinput: waiting for UI_FF_UPLOAD events will not inform user when
 allocation is required
To:     dmitry.torokhov@gmail.com, rydberg@bitmath.org
Cc:     linux-input@vger.kernel.org, linux-kernel@vger.kernel.org
Content-Type: text/plain; charset="UTF-8"
X-Spam-Status: No, score=-1.8 required=5.0 tests=BAYES_00,DKIM_SIGNED,
        DKIM_VALID,DKIM_VALID_AU,DKIM_VALID_EF,FREEMAIL_ENVFROM_END_DIGIT,
        FREEMAIL_FROM,RCVD_IN_DNSWL_BLOCKED,SPF_HELO_NONE,SPF_PASS
        autolearn=ham autolearn_force=no version=3.4.6
X-Spam-Checker-Version: SpamAssassin 3.4.6 (2021-04-09) on
        lindbergh.monkeyblade.net
Precedence: bulk
List-ID: <linux-input.vger.kernel.org>
X-Mailing-List: linux-input@vger.kernel.org

Currently the "fake" input events generated by uinput in response to
effect uploads will return an effect with an id that has already been
handled by input_ff_upload in ff-core.c, which can modify the effect
id. This causes a problem specifically when the effect originally
uploaded via the EVIOCSFF ioctl contained an effect with -1, as the
userspace code handling UI_FF_UPLOAD receives an effect with an id
other than -1, and therefore will not know an allocation was
requested.

I notice that the "old" field on the ff_effect struct is set to NULL
when the -1 id is changed (in input_ff_upload), which can serve as a
flag that an allocation was requested. If it is the intention is that
uinput users check if old == NULL to know when allocations are needed
I think uinput documentation should describe this.

I first noticed this using python-evdev, see my issue report here:
https://github.com/gvalkov/python-evdev/issues/199
