Return-Path: <linux-input-owner@vger.kernel.org>
X-Original-To: lists+linux-input@lfdr.de
Delivered-To: lists+linux-input@lfdr.de
Received: from vger.kernel.org (vger.kernel.org [23.128.96.18])
	by mail.lfdr.de (Postfix) with ESMTP id B2501407570
	for <lists+linux-input@lfdr.de>; Sat, 11 Sep 2021 09:32:52 +0200 (CEST)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S235347AbhIKHdt (ORCPT <rfc822;lists+linux-input@lfdr.de>);
        Sat, 11 Sep 2021 03:33:49 -0400
Received: from smtp-out1.suse.de ([195.135.220.28]:33032 "EHLO
        smtp-out1.suse.de" rhost-flags-OK-OK-OK-OK) by vger.kernel.org
        with ESMTP id S235213AbhIKHdo (ORCPT
        <rfc822;linux-input@vger.kernel.org>);
        Sat, 11 Sep 2021 03:33:44 -0400
Received: from relay2.suse.de (relay2.suse.de [149.44.160.134])
        by smtp-out1.suse.de (Postfix) with ESMTP id D964B2220A;
        Sat, 11 Sep 2021 07:32:29 +0000 (UTC)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=suse.de; s=susede2_rsa;
        t=1631345549; h=from:from:reply-to:date:date:message-id:message-id:to:to:cc:cc:
         mime-version:mime-version:content-type:content-type:
         in-reply-to:in-reply-to:references:references;
        bh=OFxBkbKx/5m53bCKryI4rAS9C46XmN1FDbyzEjcezrQ=;
        b=WlHkhGlbarFRLu2VXrM9eKBw600FF22MFA638fHa2IzTOJ3i8hYrJZ9RDx1uwYPOio9Q3K
        9un2fnQnWlu9ILz/M//DVPjye/eWS2qcADPl4ZJDi5WxEMqnhbKNRnaGng/SEbIeYViaok
        rISC4zrbBKmW9pubpzBG6FXRJbKgtIU=
DKIM-Signature: v=1; a=ed25519-sha256; c=relaxed/relaxed; d=suse.de;
        s=susede2_ed25519; t=1631345549;
        h=from:from:reply-to:date:date:message-id:message-id:to:to:cc:cc:
         mime-version:mime-version:content-type:content-type:
         in-reply-to:in-reply-to:references:references;
        bh=OFxBkbKx/5m53bCKryI4rAS9C46XmN1FDbyzEjcezrQ=;
        b=V99NbUCpl9N/+WeosLGeKOIMcqGG5WmeFtE4HHs70wlU9yhlgk2dLsFIbqPoCAL+UuGqZn
        C6RHJ661910p4MAQ==
Received: from alsa1.suse.de (alsa1.suse.de [10.160.4.42])
        by relay2.suse.de (Postfix) with ESMTP id D40F7A3B8F;
        Sat, 11 Sep 2021 07:32:29 +0000 (UTC)
Date:   Sat, 11 Sep 2021 09:32:29 +0200
Message-ID: <s5hee9vlg8i.wl-tiwai@suse.de>
From:   Takashi Iwai <tiwai@suse.de>
To:     Fabio Estevam <festevam@gmail.com>
Cc:     Dmitry Torokhov <dmitry.torokhov@gmail.com>,
        linux-input@vger.kernel.org
Subject: Re: Delaying i8042 probe?
In-Reply-To: <CAOMZO5CACdcxGWn++f0+zhQaKevH7b5c-Xkv3QLBpwxc2GxizQ@mail.gmail.com>
References: <s5ho890n1rh.wl-tiwai@suse.de>
        <CAOMZO5C-wFv0LmbHfZQUMMchJAwvxMxTs=eT6oby8O8k4QyoFQ@mail.gmail.com>
        <s5hee9wmy6e.wl-tiwai@suse.de>
        <CAOMZO5CACdcxGWn++f0+zhQaKevH7b5c-Xkv3QLBpwxc2GxizQ@mail.gmail.com>
User-Agent: Wanderlust/2.15.9 (Almost Unreal) SEMI/1.14.6 (Maruoka)
 FLIM/1.14.9 (=?UTF-8?B?R29qxY0=?=) APEL/10.8 Emacs/25.3
 (x86_64-suse-linux-gnu) MULE/6.0 (HANACHIRUSATO)
MIME-Version: 1.0 (generated by SEMI 1.14.6 - "Maruoka")
Content-Type: text/plain; charset=US-ASCII
Precedence: bulk
List-ID: <linux-input.vger.kernel.org>
X-Mailing-List: linux-input@vger.kernel.org

On Sat, 11 Sep 2021 03:36:21 +0200,
Fabio Estevam wrote:
> 
> On Fri, Sep 10, 2021 at 9:07 AM Takashi Iwai <tiwai@suse.de> wrote:
> 
> > Thanks, I'll try to build a test kernel and let you know the result.
> 
> Just saw the report in bugzilla and it failed like this:
> 
> [    1.015028] i8042 i8042: probe deferral not supported
> 
> This is because the driver is currently registered via platform_create_bundle().
> 
> Changing it to platform_driver_register() would allow defer probe and hopefully
> fix the problem.
> 
> Please find attached a new patch (only build-tested).

OK, I'll update and let the reporter testing it.


thanks,

Takashi
